mysql56:
  build: ./mysql56
  container_name: mysql56
  environment:
   - MYSQL_ROOT_PASSWORD=mysql56secret
  ports:
   - "9016:3306"
  volumes:
   - /data:/var/lib/mysql

nginx:
  build: ./nginx
  container_name: nginx
  ports:
   - "80:80"
  volumes:
   - /Users/javi/Documents/workspace/PhpstormProjects:/usr/share/nginx/html
  links:
   - php56
   - php70

php56:
  build: ./php56
  container_name: php56
  ports:
   - "9056:9000"
  volumes:
   - /Users/javi/Documents/workspace/PhpstormProjects:/var/www/html
  links:
   - mysql56
   - redis

php70:
  build: ./php70
  container_name: php70
  ports:
   - "9070:9000"
  volumes:
   - /Users/javi/Documents/workspace/PhpstormProjects:/var/www/html
  links:
   - mysql56
   - redis

redis:
  image: redis
  container_name: redis 
  ports:
   - "6379"
